### PR TITLE
Updated the box-border on hover

### PR DESCRIPTION
**Pull request by sansyrox**
This fixes issue #15

### CODE REVIEW

**Comment by sansyrox** [comment]
@krishnarai30 ,please have a look

**Comment by flaredragon** [comment]
can you please provide a screenshot or github pages link to verify

**Comment by sansyrox** [comment]
screen shot 2017-10-22 at 12 37 03 am
screen shot 2017-10-22 at 12 37 05 am
@flaredragon ,sorry for the delay:the blue boxes in the background on hover are of same dimensions for all the headings under our aim.

**Comment by sansyrox** [comment]
@flaredragon , https://stealthanthrax.github.io/iosd-frontend/ 
here is the link for the gh page

**Pull request merged**
